### ISSUE TITLE
I'm getting the following error when using gulp-connect-php

### ISSUE THREAD

**Issue by idanb11** [micahblu/gulp-connect-php#6]
```
Error: Cannot find module 'opn'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (...\node_modules\gulp-connect-php\index.js:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by micahblu** [comment]
This is fixed in the latest 0.0.3 version. That version is also registered with npm. Should be good to go
